// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CustomDamageFormulas","status":true,"description":"A Beginning RPG Maker VX Ace Module adapted for RPG Maker MV","parameters":{}},
{"name":"Snippets","status":true,"description":"Contains all modified code for Chapter 14's exercises.","parameters":{}}
];
